version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    command: ["mongod", "--quiet"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskmanager
      - JWT_SECRET=your_jwt_secret
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    build: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
