version: '3.8'

services:
  

  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb+srv://hamzamubeen181:hamza182@cluster0.wzgea7f.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=aetheris
      - PORT=5000
    

  # frontend:
  #   build: ./Frontend
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - backend

volumes:
  mongo-data:
